### ISSUE TITLE
noteshrink.py error

### ISSUE THREAD

**Issue by martin8877** [clapautius/noteshrink-qt#2]
Hi, 
when I open an image and click on Preview or Run I get error:
```Running command:
noteshrink.py -v 25 -p 5 -n 8 -b /tmp/noteshrink-qt-Pcp39l/noteshrink-qt-tmp -c "/bin/true" /home/mato/Pictures/1.png
Error:

```

AppImage Build
OS: Manjaro

**Comment by clapautius** [comment]
@martin8877 Do you have noteshrink.py installed? noteshrink-qt AppImage does not contain the noteshrink.py app.

If that's the case, I'll try to add a better error message.

On the other hand, in the future I'll try to provide an AppImage that includes noteshrink.py. (see issue https://github.com/clapautius/noteshrink-qt/issues/3 ).

**Comment by martin8877** [comment]
I have noteshrink installed via [AUR](https://aur.archlinux.org/packages/noteshrink/) but in my case command name is _noteshrink_ not noteshrink.py

**Comment by clapautius** [comment]
Thanks for the info. This issue should be fixed by commit https://github.com/clapautius/noteshrink-qt/commit/022d1a9d40419722c68b6d02f058e3ce1c17149d (you should be able to select a custom path for noteshrink.py binary).

**Comment by clapautius** [comment]
Beta version available at: https://github.com/clapautius/noteshrink-qt/releases/download/v8-beta/noteshrink-qt-v8-beta-x86_64.AppImage

**Comment by martin8877** [comment]
The beta version is working as expected.
Thanks.
