### ISSUE TITLE
noteshrink vs noteshrink-c?

### ISSUE THREAD

**Issue by zvezdochiot** [clapautius/noteshrink-qt#4]
Hi @clapautius .

Maybe use [noteshrink-c](https://github.com/ImageProcessing-ElectronicPublications/noteshrink-c) instead of [noteshrink](https://github.com/mzucker/noteshrink)?

Good Luck.

**Comment by clapautius** [comment]
That would be great. Much easier to integrate into one binary.

I'll definitely look into it.

**Comment by clapautius** [comment]
Backend project impossible to integrate (ATM).
